#!/usr/bin/env python3
"""
Problem 12: Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math


def count_divisors(n):
    """Count the number of divisors of n."""
    count = 0
    sqrt_n = int(math.sqrt(n))
    
    for i in range(1, sqrt_n + 1):
        if n % i == 0:
            count += 1
            if i != n // i:
                count += 1
    
    return count


def find_triangle_number_with_divisors(target_divisors):
    """Find the first triangle number with more than target_divisors divisors."""
    n = 1
    triangle = 1
    
    while True:
        num_divisors = count_divisors(triangle)
        
        if num_divisors > target_divisors:
            return triangle
        
        n += 1
        triangle += n


def main():
    """Main function to solve the problem."""
    target = 500
    result = find_triangle_number_with_divisors(target)
    
    print(f"The first triangle number to have over {target} divisors is: {result}")
    print(f"Number of divisors: {count_divisors(result)}")


if __name__ == "__main__":
    main()
